// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/guardrailsio/guardrails-cli/internal/client/guardrails (interfaces: GuardRailsClient)

// Package mockguardrailsclient is a generated GoMock package.
package mockguardrailsclient

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGuardRailsClient is a mock of GuardRailsClient interface.
type MockGuardRailsClient struct {
	ctrl     *gomock.Controller
	recorder *MockGuardRailsClientMockRecorder
}

// MockGuardRailsClientMockRecorder is the mock recorder for MockGuardRailsClient.
type MockGuardRailsClientMockRecorder struct {
	mock *MockGuardRailsClient
}

// NewMockGuardRailsClient creates a new mock instance.
func NewMockGuardRailsClient(ctrl *gomock.Controller) *MockGuardRailsClient {
	mock := &MockGuardRailsClient{ctrl: ctrl}
	mock.recorder = &MockGuardRailsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardRailsClient) EXPECT() *MockGuardRailsClientMockRecorder {
	return m.recorder
}

// CreateUploadURL mocks base method.
func (m *MockGuardRailsClient) CreateUploadURL() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploadURL")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUploadURL indicates an expected call of CreateUploadURL.
func (mr *MockGuardRailsClientMockRecorder) CreateUploadURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploadURL", reflect.TypeOf((*MockGuardRailsClient)(nil).CreateUploadURL))
}

// GetScanData mocks base method.
func (m *MockGuardRailsClient) GetScanData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanData")
	ret0, _ := ret[0].(error)
	return ret0
}

// GetScanData indicates an expected call of GetScanData.
func (mr *MockGuardRailsClientMockRecorder) GetScanData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanData", reflect.TypeOf((*MockGuardRailsClient)(nil).GetScanData))
}

// TriggerScan mocks base method.
func (m *MockGuardRailsClient) TriggerScan() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScan")
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerScan indicates an expected call of TriggerScan.
func (mr *MockGuardRailsClientMockRecorder) TriggerScan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScan", reflect.TypeOf((*MockGuardRailsClient)(nil).TriggerScan))
}

// UploadProject mocks base method.
func (m *MockGuardRailsClient) UploadProject() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProject")
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadProject indicates an expected call of UploadProject.
func (mr *MockGuardRailsClientMockRecorder) UploadProject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProject", reflect.TypeOf((*MockGuardRailsClient)(nil).UploadProject))
}
