name: GuardRails CLI Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.18"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set new version as environment variable
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set new version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sed -i -E "s/VERSION=\".*\"/VERSION=\"${{ env.VERSION }}\"/" install.sh
          git config --global user.email "wahyudi.ibo.wibowo@gmail.com"
          git config --global user.name "wahyudibo"
          git remote set-url --push origin https://wahyudibo:$GITHUB_TOKEN@github.com/wahyudibo/goreleaser-poc
          git checkout main
          git add .
          git commit -a -m "set version numbers: ${{ env.VERSION }}"
          git push origin main